const { Member, User } = require('../models');

const membersData = [
  { first_name: 'Lea', phone: '659221985' },
  { first_name: 'Janette', phone: '675598377' },
  { first_name: 'Chris', phone: '671367043' },
  { first_name: 'Dorcas', phone: '670517064' },
  { first_name: 'Mark', phone: '683929533' },
  { first_name: 'Alfred', phone: '' },
  { first_name: 'Rhoda ft', phone: '' },
  { first_name: 'Success', phone: '' },
  { first_name: 'Jessica', phone: '' },
  { first_name: 'Naomi', phone: '681618830' },
  { first_name: 'Blandine', phone: '680613794' },
  { first_name: 'Ulrich', phone: '673126814' },
  { first_name: 'Dixon', phone: '' },
  { first_name: 'Ashley', phone: '' },
  { first_name: 'Emmaculate', phone: '' },
  { first_name: 'Mama Janet', phone: '674550011' },
  { first_name: 'Gaëlle', phone: '658843192' },
  { first_name: 'Stéphane', phone: '' },
  { first_name: 'Mama Rose', phone: '' },
  { first_name: 'Esther', phone: '' },
  { first_name: 'Brandon\'s friend ft', phone: '' },
  { first_name: 'Eli', phone: '687727214' },
  { first_name: 'Miguel', phone: '659328389' },
  { first_name: 'Rhema', phone: '657986822' },
  { first_name: 'Sherry Sharon', phone: '656651328' },
  { first_name: 'Corneille', phone: '' },
  { first_name: 'Gabrielle', phone: '' },
  { first_name: 'Jessica\'s frnd', phone: '' },
  { first_name: 'Elisa', phone: '' },
  { first_name: 'Cherish', phone: '' },
  { first_name: 'Godwill', phone: '' },
  { first_name: 'Sonita', phone: '675598377' },
  { first_name: 'Melvis ft', phone: '672541231' },
  { first_name: 'Loveline', phone: '' },
  { first_name: 'Indrid FT', phone: '' },
  { first_name: 'Yann FT', phone: '' },
  { first_name: 'Caleb FT', phone: '' },
  { first_name: 'Albert FT', phone: '' },
  { first_name: 'Christabel', phone: '653645953' },
  { first_name: 'Regular\'s sis', phone: '681292523' },
  { first_name: 'Julien', phone: '' },
  { first_name: 'Ange', phone: '' },
  { first_name: 'Aimé', phone: '' },
  { first_name: 'leandre', phone: '' },
  { first_name: 'verane', phone: '' },
  { first_name: 'taylor', phone: '' },
  { first_name: 'orly', phone: '' },
  { first_name: 'rufina', phone: '' },
  { first_name: 'etienne', phone: '' },
  { first_name: 'barnabe', phone: '' },
  { first_name: 'keren', phone: '' },
  { first_name: 'akagor', phone: '' },
  { first_name: 'angel', phone: '' },
  { first_name: 'kiara', phone: '' },
  { first_name: 'paloma', phone: '' },
  { first_name: 'Paul', phone: '' },
  { first_name: 'Alfred 2', phone: '' },
  { first_name: 'Daniel', phone: '' },
  { first_name: 'Joel', phone: '' },
  { first_name: 'Mama Jacqueline', phone: '' },
  { first_name: 'Jordy', phone: '' },
  { first_name: 'Papa Sandrine', phone: '' },
  { first_name: 'Jackline', phone: '67819609' },
  { first_name: 'Blaise', phone: '676790188' },
  { first_name: 'Christelle', phone: '672923140' },
  { first_name: 'Gilbert', phone: '' },
  { first_name: 'Aunty Rose', phone: '' },
  { first_name: 'Silvic', phone: '678850369' },
  { first_name: 'Brian', phone: '679478313' },
  { first_name: 'Harmony', phone: '' },
  { first_name: 'Pamela', phone: '' },
  { first_name: 'Claudia', phone: '650853378' },
  { first_name: 'Marcel', phone: '' },
  { first_name: 'Manoela', phone: '' },
  { first_name: 'Leticia', phone: '' },
  { first_name: 'Brice', phone: '' },
  { first_name: 'Adrian', phone: '' },
  { first_name: 'Samira', phone: '' },
  { first_name: 'Sandra ft', phone: '' },
  { first_name: 'Jaden', phone: '677746981' },
  { first_name: 'Simonie ft', phone: '' },
  { first_name: 'Mama Blaise', phone: '' },
  { first_name: 'Ruth', phone: '' },
  { first_name: 'Laura', phone: '674990369' },
  { first_name: 'Carlson', phone: '650818120' },
  { first_name: 'Ncheh', phone: '' },
  { first_name: 'Rudeph', phone: '671898738' },
  { first_name: 'Francisco', phone: '693923917' },
  { first_name: 'Jessy', phone: '' },
  { first_name: 'Brian II', phone: '' },
  { first_name: 'Yvette', phone: '' },
  { first_name: 'Louis', phone: '' },
  { first_name: 'Edwige', phone: '' },
  { first_name: 'Namel', phone: '' },
  { first_name: 'Leonard', phone: '651215253' },
  { first_name: 'Nancy', phone: '676709747' },
  { first_name: 'Veronique ft', phone: '' },
  { first_name: 'Blaise tenant ft', phone: '' },
  { first_name: 'Alexia', phone: '' },
  { first_name: 'Alicia ft', phone: '697962193' },
  { first_name: 'Tayong ft', phone: '' },
  { first_name: 'Rita ft', phone: '' },
  { first_name: 'Ruth friend', phone: '' },
  { first_name: 'Blaise soul ft', phone: '' },
  { first_name: 'Brian soul', phone: '' },
  { first_name: 'Rejoice', phone: '' },
  { first_name: 'Paloma 2', phone: '696500125' },
  { first_name: 'Cyril', phone: '' },
  { first_name: 'Nelson', phone: '653197226' },
  { first_name: 'Cynthia', phone: '692815522' },
  { first_name: 'Christy', phone: '640052425' },
  { first_name: 'Chelcy', phone: '652881423' },
  { first_name: 'Javis', phone: '679133338' },
  { first_name: 'Tomfon', phone: '' },
  { first_name: 'Eva', phone: '697385135' },
  { first_name: 'Negoza', phone: '' },
  { first_name: 'Shekina', phone: '693540650' },
  { first_name: 'Joslin', phone: '' },
  { first_name: 'Rev T', phone: '676046068' },
  { first_name: 'Enou', phone: '657321115' },
  { first_name: 'Stéphane 2', phone: '' },
  { first_name: 'Princewill', phone: '' },
  { first_name: 'Divine', phone: '' },
  { first_name: 'Mama Ruth', phone: '' },
  { first_name: 'Shekina neighbor', phone: '' },
  { first_name: 'Pauline', phone: '' },
  { first_name: 'Chelsea', phone: '' },
  { first_name: 'Eva friend', phone: '' },
  { first_name: 'Sandrine', phone: '' },
  { first_name: 'Aso', phone: '' },
  { first_name: 'Tailor ft', phone: '' },
  { first_name: 'New soul', phone: '' },
  { first_name: 'Rolphine ft', phone: '' },
  { first_name: 'Ruth 2', phone: '' },
  { first_name: 'Erlosa ft', phone: '676132310' },
  { first_name: 'Jean ft', phone: '' },
  { first_name: 'Shekina soul ft', phone: '' },
  { first_name: 'Vivian ft', phone: '' },
  { first_name: 'Prisca', phone: '675073068' },
  { first_name: 'Precious', phone: '' },
  { first_name: 'Sonita 2', phone: '675598377' },
  { first_name: 'Vannina ft', phone: '694806501' },
  { first_name: 'Jonathan', phone: '' },
  { first_name: 'Synthla', phone: '' },
  { first_name: 'Glenn ft', phone: '' },
  { first_name: 'Naomi 2', phone: '681602311' },
  { first_name: 'Pride', phone: '693427192' },
  { first_name: 'mama Janet 2', phone: '674550011' },
  { first_name: 'Brandon', phone: '697960374' },
  { first_name: 'Franklin', phone: '698886368' },
  { first_name: 'William', phone: '674022505' },
  { first_name: 'Rachelle', phone: '' },
  { first_name: 'Solange', phone: '' },
  { first_name: 'Shillo', phone: '' },
  { first_name: 'Rita', phone: '' },
  { first_name: 'Rayson', phone: '' },
  { first_name: 'Ramsey', phone: '' },
  { first_name: 'Hema ft', phone: '' },
  { first_name: 'Sharon', phone: '' },
  { first_name: 'Cathy ft', phone: '696545153' },
  { first_name: 'Destinee', phone: '' },
  { first_name: 'Atangana ft', phone: '' },
  { first_name: 'Blaise mom', phone: '' },
  { first_name: 'Blaise dad', phone: '' },
  { first_name: 'Axcel ft', phone: '' },
  { first_name: 'Exctor ft', phone: '' },
  { first_name: 'Fri Sandra ft', phone: '651736761' },
  { first_name: 'Tracey ft', phone: '676570348' },
  { first_name: 'Triomphe ft', phone: '' },
  { first_name: 'William ii', phone: '696545153' },
  { first_name: 'chanceline', phone: '' },
  { first_name: 'Maxwell', phone: '' },
  { first_name: 'Dorcas mom', phone: '' },
  { first_name: 'Kelly', phone: '' },
  { first_name: 'Ange ft', phone: '' },
  { first_name: 'Manuella ft', phone: '673105474' },
  { first_name: 'Rose 2', phone: '676831701' },
  { first_name: 'Clifford ft', phone: '' },
  { first_name: 'Stéphane ft 3', phone: '' },
  { first_name: 'Kiara', phone: '' },
  { first_name: 'Delight', phone: '671837042' },
  { first_name: 'Fon', phone: '693760378' },
  { first_name: 'Vanessa', phone: '694806584' },
  { first_name: 'Sonia 2', phone: '690801259' },
  { first_name: 'Grace', phone: '' },
  { first_name: 'Flore FT', phone: '695705353' },
  { first_name: 'Mac Bright', phone: '' },
  { first_name: 'Eksong', phone: '' },
  { first_name: 'Shaline', phone: '' },
  { first_name: 'Spencer', phone: '' },
  { first_name: 'Emmanuel', phone: '' },
  { first_name: 'Veron', phone: '' },
  { first_name: 'Gloria', phone: '' },
  { first_name: 'Carlie', phone: '' },
  { first_name: 'Leona', phone: '' },
  { first_name: 'Nnaloa', phone: '' },
  { first_name: 'Miranda', phone: '' },
  { first_name: 'Claris', phone: '' },
  { first_name: 'Mabel', phone: '' },
  { first_name: 'Eloise', phone: '' },
  { first_name: 'chanceline lower', phone: '' },
  { first_name: 'label', phone: '' },
  { first_name: 'ada', phone: '' },
  { first_name: 'marcel 2', phone: '' },
  { first_name: 'justin', phone: '' },
  { first_name: 'madeleine', phone: '' },
  { first_name: 'mama blaise 2', phone: '' },
  { first_name: 'slim', phone: '' },
  { first_name: 'Yvette', phone: '' },
  { first_name: 'mendj', phone: '' },
  { first_name: 'sons junior', phone: '' },
  { first_name: 'blessing', phone: '' },
  { first_name: 'daniela', phone: '' },
  { first_name: 'madeleine 2', phone: '' },
  { first_name: 'lower', phone: '' },
  { first_name: 'noella', phone: '' },
  { first_name: 'marcel 3', phone: '' },
  { first_name: 'Prince', phone: '' },
  { first_name: 'nica', phone: '' }
];

async function importTraceyMembers(traceyId, areaId) {
  let imported = 0;
  let skipped = 0;
  let updated = 0;
  let errors = [];
  
  if (!areaId) {
    return { error: 'Leader/Governor n a pas de zone assignée.' };
  }

  for (const m of membersData) {
    try {
      const cleanFirstName = m.first_name.trim();
      
      const existingMember = await Member.findOne({
        where: {
          first_name: cleanFirstName,
          leader_id: traceyId
        }
      });

      if (existingMember) {
        await existingMember.update({ service_type: 'GES' });
        updated++;
      } else {
        await Member.create({
          first_name: cleanFirstName,
          last_name: 'Inconnu',
          phone_primary: m.phone || '000000000',
          gender: 'Unknown',
          service_type: 'GES',
          area_id: areaId,
          leader_id: traceyId,
          is_active: true
        });
        imported++;
      }
    } catch (error) {
      console.error(`Error importing ${m.first_name}:`, error.message);
      if (errors.length < 5) {
        errors.push(`${m.first_name}: ${error.message}`);
      }
      skipped++;
    }
  }

  // Fallback: update ALL of Tracey's existing members to GES
  await Member.update(
    { service_type: 'GES' },
    { where: { leader_id: traceyId } }
  );

  return { imported, updated, skipped, total: membersData.length, errors };
}

module.exports = { importTraceyMembers };
