const { Member, User } = require('../models');

const membersData = [
  // Image 1
  { first_name: 'Dorian', phone: '674394132' },
  { first_name: 'Relindis', phone: '677250424' },
  { first_name: 'Alice Princes sister', phone: '' },
  { first_name: 'Marikaa Prince wife', phone: '678428403' },
  { first_name: 'Mr Prince', phone: '676268151' },
  { first_name: 'Rapha', phone: '' },
  { first_name: 'Nadège P.', phone: '' },
  { first_name: 'Nadège sister', phone: '' },
  { first_name: 'Gracious', phone: '' },
  { first_name: 'Remi', phone: '' },
  { first_name: 'Mama Glory', phone: '' },
  { first_name: 'Glory', phone: '' },
  { first_name: 'Alice 2', phone: '' },
  { first_name: 'Sandrine', phone: '' },
  { first_name: 'Clinton', phone: '' },
  { first_name: 'Blessing', phone: '' },
  { first_name: 'Julles', phone: '' },
  { first_name: 'Kelvin Ft', phone: '' },
  { first_name: 'Shoroline', phone: '' },
  { first_name: 'Destiny', phone: '677224344' },
  { first_name: 'Divine', phone: '' },
  { first_name: 'Divine friend', phone: '' },
  { first_name: 'Angel', phone: '' },
  { first_name: 'Ps Sam', phone: '' },
  { first_name: 'Lp Ornella', phone: '682748547' },
  { first_name: 'Glory Mama', phone: '692888808' },
  { first_name: 'Bryan', phone: '' },
  { first_name: 'Tina Monique', phone: '677568333' },
  { first_name: 'Emmanu', phone: '' },
  { first_name: 'Thierry', phone: '' },
  { first_name: 'Maryflowers', phone: '' },
  { first_name: 'Rose Perfection', phone: '659322123' },
  { first_name: 'Raïsa', phone: '' },
  { first_name: 'Etel', phone: '' },
  { first_name: 'Mr Orock', phone: '' },
  { first_name: 'Mrs Orock', phone: '' },
  { first_name: 'Céline', phone: '675274191' },
  { first_name: 'Mrs Mamrey', phone: '77455799' },
  { first_name: 'Ako', phone: '' },
  { first_name: 'Agbor', phone: '682710707' },
  { first_name: 'Gladys', phone: '' },
  { first_name: 'Ledvine', phone: '' },
  { first_name: 'Akem', phone: '' },
  { first_name: 'Prisca', phone: '' },
  { first_name: 'Elizabeth', phone: '682740547' },
  { first_name: 'Brenda', phone: '' },
  { first_name: 'Blossom', phone: '' },
  { first_name: 'Azeh', phone: '' },
  { first_name: 'Rose', phone: '' },
  { first_name: 'Megan', phone: '' },
  { first_name: 'Delmas', phone: '670355374' },
  { first_name: 'olivette', phone: '' },
  { first_name: 'Chiedi', phone: '655529251' },
  { first_name: 'James', phone: '' },
  { first_name: 'Maria', phone: '' },
  { first_name: 'Ashley', phone: '' },
  { first_name: 'Immaculate Ft', phone: '' },
  { first_name: 'Braina', phone: '' },
  { first_name: 'Théophile', phone: '' },
  { first_name: 'Gwan', phone: '' },
  { first_name: 'Juliette', phone: '' },
  { first_name: 'Treasure', phone: '693441981' },
  { first_name: 'Thelma', phone: '' },
  { first_name: 'Terry', phone: '' },
  { first_name: 'Comfort', phone: '' },
  { first_name: 'Mr Lyonga', phone: '677468798' },
  { first_name: 'Boris', phone: '' },
  { first_name: 'Nadine', phone: '' },
  { first_name: 'Glory Orock', phone: '' },
  { first_name: 'Enow Orock', phone: '' },
  { first_name: 'Success Adele', phone: '' },
  { first_name: 'Fritz', phone: '' },
  { first_name: 'Prince', phone: '676266151' },
  { first_name: 'Marika Prince', phone: '678428403' },
  { first_name: 'Alice', phone: '' },
  { first_name: 'Rapha', phone: '' },
  { first_name: 'Tambi', phone: '653728552' },
  { first_name: 'Christina', phone: '' },
  { first_name: 'Serge', phone: '' },
  { first_name: 'Bless', phone: '' },
  { first_name: 'Maryflower\'s nephew', phone: '' },
  { first_name: 'Helena', phone: '' },
  { first_name: 'Stacy', phone: '' },
  { first_name: 'Ellora', phone: '' },
  { first_name: 'Seraphin', phone: '' },
  { first_name: 'Liz', phone: '' },
  { first_name: 'Elodie', phone: '656004908' },
  { first_name: 'Robinson', phone: '677274768' },
  { first_name: 'Ndim Miranda', phone: '479426809' },

  // Image 2
  { first_name: 'Juvani', phone: '' },
  { first_name: 'Ma Joan', phone: '' },
  { first_name: 'Sarah', phone: '' },
  { first_name: 'Aunty Favour', phone: '' },
  { first_name: 'Sylvia', phone: '679816165' },
  { first_name: 'Alvera', phone: '' },
  { first_name: 'Bryan Ebai', phone: '' },
  { first_name: 'Emilia 1.', phone: '653724642' },
  { first_name: 'Laura', phone: '' },
  { first_name: 'Sarah 2', phone: '' },
  { first_name: 'Gladness', phone: '' },
  { first_name: 'Eunice', phone: '' },
  { first_name: 'Leticia', phone: '' },
  { first_name: 'Herve ft', phone: '658052303' },
  { first_name: 'Claudia FT', phone: '' },
  { first_name: 'Francesca Ft', phone: '' },
  { first_name: 'Emilia 2 ft', phone: '' },
  { first_name: 'Brenda Ft', phone: '654176565' },
  { first_name: 'Sandra', phone: '' },
  { first_name: 'Giovanni', phone: '' },
  { first_name: 'Perpetua', phone: '' },
  { first_name: 'Carine', phone: '' },
  { first_name: 'Emilia husband', phone: '' },
  { first_name: 'Olivia', phone: '' },
  { first_name: 'Mughang Jolle', phone: '671663359' },
  { first_name: 'Nico', phone: '' },
  { first_name: 'sinorine', phone: '' },
  { first_name: 'Faith', phone: '676318373' },
  { first_name: 'Mary', phone: '' },
  { first_name: 'Vanessa', phone: '' },
  { first_name: 'Marie Claire', phone: '' },
  { first_name: 'Kima Miranda', phone: '651247962' },
  { first_name: 'Samantha', phone: '699447064' },
  { first_name: 'Bimi Balde', phone: '671726413' },
  { first_name: 'Njoyo Dimitri', phone: '680469369' },
  { first_name: 'Brice', phone: '671726413' },
  { first_name: 'Nde Princely', phone: '678353852' },
  { first_name: 'Vivian Xaah', phone: '678503016' },
  { first_name: 'Glory Frida', phone: '672595852' },
  { first_name: 'Nakou Sinphorine', phone: '680743551' },
  { first_name: 'Blondelle', phone: '' },
  { first_name: 'Geraldine', phone: '' },
  { first_name: 'Alex', phone: '672888868' },
  { first_name: 'Clovis', phone: '' },
  { first_name: 'Titus', phone: '679720817' },
  { first_name: 'Carmane', phone: '653237762' },
  { first_name: 'Destiny 2', phone: '653853722' },
  { first_name: 'Akos', phone: '651569034' },
  { first_name: 'Blondel', phone: '656622864' },
  { first_name: 'Pierre', phone: '657383280' },
  { first_name: 'LP Marie Noëlle', phone: '' },
  { first_name: 'Clara Enow', phone: '' },
  { first_name: 'Alice. Enow', phone: '650389404' },
  { first_name: 'Margaret Enow', phone: '673762209' },
  { first_name: 'Mama Nanaoua', phone: '' },
  { first_name: 'James Nanaoua', phone: '' },
  { first_name: 'Chérubin Nanaoua', phone: '' },
  { first_name: 'Irene FT', phone: '657160815' },
  { first_name: 'Ange Ft', phone: '659446886' },
  { first_name: 'Ayamba', phone: '' },
  { first_name: 'Mama Marie 2', phone: '697729427' },

  // Image 3
  { first_name: 'Dr Nkumbe', phone: '' },
  { first_name: 'Mrs Nkumbe Akos', phone: '' },
  { first_name: 'Mama Akos', phone: '' },
  { first_name: 'Daniella', phone: '' },
  { first_name: 'Nathan', phone: '' },
  { first_name: 'Max', phone: '' },
  { first_name: 'Bridget Kubrl', phone: '677465751' },
  { first_name: 'Regina Ashu', phone: '' },
  { first_name: 'Stephanie Tenkue', phone: '' },
  { first_name: 'Lawrencia', phone: '' },
  { first_name: 'Mayel', phone: '' },
  { first_name: 'Bernard', phone: '698291706' },
  { first_name: 'Biri\'s sister', phone: '' },
  { first_name: 'Brian 2', phone: '' },
  { first_name: 'Jacky', phone: '' },
  { first_name: 'Jodel', phone: '' },
  { first_name: 'Noela', phone: '' },
  { first_name: 'Evert', phone: '' },
  { first_name: 'Cedric', phone: '' },
  { first_name: 'Agbor 2', phone: '682710707' },
  { first_name: 'Ashu Maurice', phone: '673220754' },
  { first_name: 'Dr Kia Bibanke', phone: '' },
  { first_name: 'Claude', phone: '' },
  { first_name: 'Dimitri', phone: '657505110' },
  { first_name: 'Brice 2', phone: '' },
  { first_name: 'Brenda 2', phone: '' },
  { first_name: 'Jean Perez', phone: '677132822' },
  { first_name: 'Rev Philip', phone: '675468467' },
  { first_name: 'Zuby', phone: '' },
  { first_name: 'Rebecca', phone: '' },
  { first_name: 'Lydia', phone: '' },
  { first_name: 'Angel 2', phone: '' },
  { first_name: 'Bibiana', phone: '676804354' },
  { first_name: 'Laureta', phone: '683511917' },
  { first_name: 'Moses', phone: '' },
  { first_name: 'Joyce', phone: '695413123' },
  { first_name: 'Favour 2', phone: '' },
  { first_name: 'Franka', phone: '' },
  { first_name: 'Passy', phone: '' },
  { first_name: 'Patience', phone: '' },
  { first_name: 'Juliette 2', phone: '' },
  { first_name: 'Leonel', phone: '692990034' },
  { first_name: 'Flourish', phone: '683628868' },
  { first_name: 'Léonard', phone: '674977793' },
  { first_name: 'Mama Joyce', phone: '674977793' },
  { first_name: 'Miguel', phone: '693542981' },
  { first_name: 'Zebaze Fortune', phone: '657112332' },
  { first_name: 'Princesse Fortuna', phone: '657112332' },
  { first_name: 'Marie 2', phone: '657112332' },
  { first_name: 'Brice 3', phone: '' },
  { first_name: 'Carole', phone: '688204828' },
  { first_name: 'Marvelous', phone: '688204828' },
  { first_name: 'Leo\'s mother', phone: '' },
  { first_name: 'Petro', phone: '' },
  { first_name: 'Ngassam', phone: '' },
  { first_name: 'Annie', phone: '' },
  { first_name: 'Maya', phone: '' },
  { first_name: 'Ma\'a Leonard', phone: '' },
  { first_name: 'Happiness', phone: '' },
  { first_name: 'Danielle', phone: '' },
  { first_name: 'Stéphane', phone: '' },
  { first_name: 'Chanelle Kyia', phone: '650613316' },
  { first_name: 'Franky', phone: '650613316' },
  { first_name: 'Meguim', phone: '657112332' },
  { first_name: 'Blanche', phone: '687284371' },
  { first_name: 'Samantha 2', phone: '699447064' },
  { first_name: 'Beltha', phone: '' },
  { first_name: 'Rose 2', phone: '' },
  { first_name: 'Victoire', phone: '' },
  { first_name: 'Michelle', phone: '' },
  { first_name: 'Bibi\'s brother', phone: '' },
  { first_name: 'Bibi\'s friend', phone: '' },
  { first_name: 'Erasmus', phone: '' },
  { first_name: 'Yolande', phone: '658083056' },
  { first_name: 'Morel', phone: '' },
  { first_name: 'Ma\'a Angeline', phone: '697756882' },
  { first_name: 'Sarah 3', phone: '' },

  // Image 4
  { first_name: 'Bika', phone: '' },
  { first_name: 'Ma\'a Vedette', phone: '670881245' },
  { first_name: 'Maelle', phone: '' },
  { first_name: 'Naomi', phone: '' },
  { first_name: 'Princess', phone: '' },
  { first_name: 'David', phone: '' },
  { first_name: 'Kerrick', phone: '' },
  { first_name: 'Marcel', phone: '' },
  { first_name: 'Faloma', phone: '' },
  { first_name: 'Bryan 3', phone: '' },
  { first_name: 'Ange 2', phone: '' },
  { first_name: 'Serena', phone: '' },
  { first_name: 'Lael', phone: '' },
  { first_name: 'Blossom 2', phone: '' },
  { first_name: 'Samira', phone: '688535011' },
  { first_name: 'Jolina', phone: '681197122' },
  { first_name: 'Ronaldo', phone: '679860415' },
  { first_name: 'Valdo', phone: '' },
  { first_name: 'Julian', phone: '' },
  { first_name: 'Joel', phone: '' },
  { first_name: 'Priscilla 2', phone: '' },
  { first_name: 'Jeanette', phone: '' },
  { first_name: 'Jaden', phone: '' },
  { first_name: 'Lionel', phone: '692990034' },
  { first_name: 'Neris', phone: '697516621' },
  { first_name: 'Nexts', phone: '' },
  { first_name: 'Borel', phone: '' },
  { first_name: 'Bobo', phone: '692249577' },
  { first_name: 'Quera', phone: '' },
  { first_name: 'Amis Quera', phone: '' },
  { first_name: 'Gloria', phone: '' },
  { first_name: 'Jordan', phone: '' },
  { first_name: 'Grand Ma', phone: '' },
  { first_name: 'Darline', phone: '' },
  { first_name: 'Christian', phone: '' },
  { first_name: 'Treasure 2', phone: '693441981' },
  { first_name: 'Ivana', phone: '' },
  { first_name: 'Aziz', phone: '' },
  { first_name: 'Gaby', phone: '' },
  { first_name: 'Michael', phone: '673983899' },
  { first_name: 'Vanessa 2', phone: '673316321' },
  { first_name: 'Culbert', phone: '699360054' },
  { first_name: 'Victoire 2', phone: '671357080' },
  { first_name: 'Dous', phone: '659291210' },
  { first_name: 'Mimi', phone: '' },
  { first_name: 'Jolina 2', phone: '' },
  { first_name: 'Damaris', phone: '' },
  { first_name: 'Mama Elsa', phone: '' },
  { first_name: 'Ambassador', phone: '' },
  { first_name: 'Bibiana\'s brother', phone: '' },

  // Image 5
  { first_name: 'pa Martin', phone: '' },
  { first_name: 'Janette 2', phone: '' },
  { first_name: 'ma\'a Jeannette', phone: '' },
  { first_name: 'Blessing 2', phone: '653336568' },
  { first_name: 'Sarah 4', phone: '' },
  { first_name: 'Lp Stella', phone: '' },
  { first_name: 'Joseph', phone: '' },
  { first_name: 'Jeanette 2', phone: '' },
  { first_name: 'Pa Jeanette', phone: '' },
  { first_name: 'Jaden 2', phone: '' },
  { first_name: 'Zita', phone: '' },
  { first_name: 'Favour 3', phone: '' },
  { first_name: 'Stephanie', phone: '' },
  { first_name: 'Precious', phone: '' },
  { first_name: 'Beatrice', phone: '682377122' },
  { first_name: 'Emilia', phone: '' },
  { first_name: 'Laura 2', phone: '' },
  { first_name: 'Sarah 5', phone: '' },
  { first_name: 'Gladness 2', phone: '' },
  { first_name: 'Favour 2 2', phone: '653045809' },
  { first_name: 'Sylvia 2', phone: '' },
  { first_name: 'Faith 2', phone: '676318373' },
  { first_name: 'Ivana 2', phone: '658074322' },
  { first_name: 'Cassandre', phone: '658074322' },
  { first_name: 'Ruth', phone: '658074322' },
  { first_name: 'Rachel', phone: '' },
  { first_name: 'Brandon', phone: '671770638' },
  { first_name: 'John', phone: '' },
  { first_name: 'Musa', phone: '' },
  { first_name: 'Suzane', phone: '652188273' },
  { first_name: 'Cusinatou', phone: '' }
];

async function importSamuelJESMembers(samuelId, areaId) {
  let imported = 0;
  let skipped = 0;
  let updated = 0;
  let errors = [];
  
  if (!areaId) {
    return { error: 'Leader/Governor n a pas de zone assignée.' };
  }

  for (const m of membersData) {
    try {
      // Removing any suffix numbers added for visual dupes to check in db
      const baseName = m.first_name.replace(/\s\d$/, '').trim();
      
      const existingMember = await Member.findOne({
        where: {
          first_name: baseName,
          leader_id: samuelId
        }
      });

      if (existingMember) {
        await existingMember.update({ service_type: 'JES' });
        updated++;
      } else {
        await Member.create({
          first_name: baseName,
          last_name: 'Inconnu',
          phone_primary: m.phone ? m.phone.replace(/\s+/g, '') : '000000000',
          gender: 'Unknown',
          service_type: 'JES',
          area_id: areaId,
          leader_id: samuelId,
          is_active: true
        });
        imported++;
      }
    } catch (error) {
      console.error(`Error importing ${m.first_name}:`, error.message);
      if (errors.length < 5) {
        errors.push(`${m.first_name}: ${error.message}`);
      }
      skipped++;
    }
  }

  // Fallback: Force update all existings 
  await Member.update(
    { service_type: 'JES' },
    { where: { leader_id: samuelId } }
  );

  return { imported, updated, skipped, total: membersData.length, errors };
}

module.exports = { importSamuelJESMembers };
